datamodule:
  batch_size: 10
  num_workers: 0
  pin_memory: False
  bands: null
  # bands:
  #   - 8
  #   - 2
  #   - 1
  indices:
    - ndvi
    - ndwi
    - ndwbi
    - mndwi
    - ioi

trainer:
  max_epochs: 10
  overfit_batches: 1
  devices:
    - 1