trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 50

datamodule:
  batch_size: 8
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomRotate90:
      p: 0.5
  bands:
    - 8 
    - 2 
    - 1

model: maxvit_base_tf_512

scheduler: 
  OneCycleLR:
    max_lr: 0.0001
    total_steps: 50
    pct_start: 0.05
    verbose: True

