trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 100

datamodule:
  batch_size: 8
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomRotate90:
      p: 0.5

model: maxvit_base_tf_512

optimizer: AdamW
optimizer_params:
  lr: 0.0003

scheduler: OneCycleLR
scheduler_params:
  max_lr: 0.0003
  total_steps: 100
  pct_start: 0.02
  verbose: True