trainer:
  logger: False
  enable_checkpointing: False 
  max_epochs: 50

datamodule:
  batch_size: 8
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomRotate90:
      p: 0.5
  bands: null

model: maxvit_base_tf_512

scheduler: 
  OneCycleLR:
    max_lr: 0.0001
    total_steps: 50
    pct_start: 0.05
    verbose: True

