trainer:
  logger: False
  enable_checkpointing: False 
  max_epochs: 30

datamodule:
  batch_size: 32
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomRotate90:
      p: 0.5

model: maxvit_large_tf_512

scheduler: OneCycleLR
scheduler_params:
    max_lr: 0.001
    total_steps: 30
    pct_start: 0.05
    verbose: True

freeze: True