datamodule:
  Dataset: DatasetFCIm
  batch_size: 4
  num_workers: 0
  pin_memory: False

trainer:
  max_epochs: 1
  overfit_batches: 1
  deterministic: False
  devices:
    - 1

in_chans: 5
mask_loss: True
encoder: resnet18
architecture: MyUnet
pafpn: True