datamodule:
  Dataset: DatasetFCIm
  batch_size: 4
  num_workers: 0
  pin_memory: False

trainer:
  max_epochs: 100
  overfit_batches: 1
  deterministic: False
  devices:
    - 1

in_chans: 5
mask_loss: True
encoder: resnest50d
architecture: MyUnet
padding: 2
upsample: True