trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 30

datamodule:
  Dataset: DatasetFCIm
  batch_size: 16

in_chans: 5
mask_loss: True
encoder: maxvit_small_tf_384
architecture: MyUnet
optimizer: AdamW
optimizer_params:
  lr: 0.0003
scheduler: 
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 30
    pct_start: 0.1
    verbose: True