trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 200

datamodule:
  Dataset: DatasetFCIm
  batch_size: 32
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomRotate90:
      p: 0.5
      
in_chans: 5
mask_loss: True
encoder: resnest50d
architecture: MyUnet
optimizer: AdamW
optimizer_params:
  lr: 0.0005
scheduler: 
  OneCycleLR:
    max_lr: 0.0005
    total_steps: 200
    pct_start: 0.1
    verbose: True