trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 30
  deterministic: False

datamodule:
  Dataset: DatasetFCIm
  batch_size: 16

padding: 2
upsample: True
in_chans: 5
mask_loss: True
encoder: resnest50d
architecture: MyUnet
optimizer: AdamW
optimizer_params:
  lr: 0.0003
scheduler: 
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 30
    pct_start: 0.1
    verbose: True