trainer:
  logger: True
  enable_checkpointing: True 

datamodule:
  Dataset: DatasetFCIm
  batch_size: 32
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomResizedCrop: 
      p: 0.5
      height: 350 
      width: 350


in_chans: 5
mask_loss: True
encoder: timm-resnest50d
architecture: UnetPlusPlus