trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 30

datamodule:
  Dataset: DatasetFCIm
  batch_size: 16 # focal loss me peta la memoria con 32, y con 16 entra por los pelos (mala implementación?)

in_chans: 5
mask_loss: True
encoder: timm-resnest50d
architecture: UnetPlusPlus
loss: focal
optimizer: AdamW
optimizer_params:
  lr: 0.0003
scheduler: 
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 30
    pct_start: 0.1
    verbose: True