trainer:
  logger: True
  enable_checkpointing: True 
  max_epochs: 16

datamodule:
  Dataset: DatasetFCIm
  batch_size: 32
  val_size: 0

in_chans: 5
mask_loss: True
encoder: timm-resnest50d
architecture: UnetPlusPlus
optimizer: AdamW
optimizer_params:
  lr: 0.0003
scheduler: 
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 30
    pct_start: 0.1
    verbose: True