trainer:
  logger: True
  enable_checkpointing: True 

datamodule:
  Dataset: DatasetFCIm
  batch_size: 32
  filter_train: ignore_train.csv


in_chans: 5
mask_loss: True
encoder: timm-resnest50d
architecture: UnetPlusPlus