trainer:
  logger: True
  limit_train_batches: 30
  limit_val_batches: 10
  log_every_n_steps: 5

datamodule:
  batch_size: 4
  months:
    - April
    - May
    - June

seq_len: 3
module: Transformer
embed_dim: 256
n_heads: 4
num_blocks: 0
