in_channels: 3

datamodule:
  batch_size: 1
  num_workers: 0
  pin_memory: False
  train_trans: null
  sensor: S2
  bands:
    - 2
    - 1
    - 0

trainer:
  max_epochs: 1000
  overfit_batches: 1

optimizer_params:
  lr: 0.001
