trainer:
  logger: True
  enable_checkpointing: True
  max_epochs: 500
  gpus: 2
  strategy: dp
  resume_from_checkpoint: checkpoints/dftar50-epoch=275.ckpt

optimizer_params:
  lr: 0.001

scheduler:
  OneCycleLR:
    max_lr: 0.001
    total_steps: 500
    pct_start: 0.01
    final_div_factor: 10
    verbose: True

encoder: timm-resnest50d
