trainer:
  logger: True
  enable_checkpointing: True
  max_epochs: 500

optimizer_params:
  lr: 0.0003

scheduler:
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 500
    pct_start: 0.2
    final_div_factor: 10
