trainer:
  logger: True 
  enable_checkpointing: True 
  max_epochs: 10
  accumulate_grad_batches: 2

encoder: convnextv2_base

optimizer_params:
  lr: 1.0e-4 

load_from_checkpoint: checkpoints/convextv2_crops-val_metric=0.61242-epoch=6.ckpt

datamodule:
  batch_size: 32
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomResizedCrop: 
      height: 256 
      width: 256


scheduler: 
  CosineAnnealingLR:
    T_max: 20
    eta_min: 1.0e-05
    last_epoch: -1
    verbose: True