trainer:
  logger: True 
  enable_checkpointing: True 
  accumulate_grad_batches: 4

encoder: convnextv2_base

optimizer_params:
  lr: 1.0e-4 

load_from_checkpoint: checkpoints/convextv2_crops-val_metric=0.61242-epoch=6.ckpt

datamodule:
  batch_size: 16
  input_size: 384
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomResizedCrop: 
      p: 0.5
      height: 256 
      width: 256
    