trainer:
  logger: True 
  enable_checkpointing: True 

encoder: convnextv2_base

optimizer_params:
  lr: 1.0e-4 

load_from_checkpoint: checkpoints/convextv2_base-val_metric=0.58134-epoch=3.ckpt

datamodule:
  batch_size: 32
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5
    # RandomResizedCrop: 
    #   height: 512 
    #   width: 512