trainer:
  logger: False
  enable_checkpointing: False
  max_epochs: 100

datamodule:
  false_color: True
  batch_size: 16
  t: 
    - 4
  train_trans: 
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomResizedCrop: 
      height: 512 
      width: 512
  val_trans:
    Resize:
      height: 512 
      width: 512

encoder: seresnextaa101d_32x8d
load_from_checkpoint: checkpoints/fc_t5_seresnextaa101d_32x8d_512-val_metric=0.58112-epoch=72.ckpt

scheduler:
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 100
    pct_start: 0.03
    final_div_factor: 10 
    verbose: True