trainer:
  logger: True
  enable_checkpointing: True

datamodule:
  false_color: True
  t: 
    - 3
    - 4
    - 5

encoder: resnest26d
optimizer_params:
  lr: 0.0003

ckpt_path: checkpoints/fc_temp_resnest26d-epoch=22.ckpt