trainer:
  logger: True
  enable_checkpointing: True

datamodule:
  false_color: True
  t: 
    - 3
    - 4
    - 5

encoder: resnest26d
optimizer_params:
  lr: 0.0003

scheduler:
  OneCycleLR:
    max_lr: 0.0003
    total_steps: 100
    pct_start: 0.03
    final_div_factor: 100 
    verbose: True