trainer:
  logger: True
  enable_checkpointing: True

datamodule:
  false_color: True
  t: 
    - 4
  train_trans: 
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5
    Resize: 
      height: 512 
      width: 512
  val_trans:
    Resize:
      height: 512 
      width: 512

encoder: resnest26d
optimizer_params:
  lr: 0.0003