trainer:
  logger: True
  enable_checkpointing: True
  max_epochs: 300

datamodule:
  false_color: True
  t: 
    - 4
  train_trans: 
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5


encoder: efficientnet_b0

loss: focal
optimizer_params:
  lr: 0.0003
