trainer:
  logger: True 
  enable_checkpointing: True 
  max_epochs: 30
  accumulate_grad_batches: 2

datamodule:
  t: 
    - 4
  batch_size: 4
  input_size: 512

encoder: maxvit_large_tf_512

optimizer: AdamW
optimizer_params:
  lr: 2.0e-05

scheduler: 
  CosineAnnealingLR:
    T_max: 30
    eta_min: 2.0e-06
    last_epoch: -1 
