trainer:
  logger: True 
  enable_checkpointing: True 

datamodule:
  t: 
    - 2
    - 3 
    - 4
  batch_size: 32
  train_trans:
    Resize:
      width: 384 
      height: 384
  val_trans:
    Resize:
      width: 384 
      height: 384

encoder: resnet34