trainer:
  logger: True 
  enable_checkpointing: True 
  max_epochs: 30

datamodule:
  t: 
    - 4
  batch_size: 32
  input_size:
    width: 384 
    height: 384

encoder: resnest50d

optimizer: AdamW
optimizer_params:
  lr: 0.0005

scheduler: 
  CosineAnnealingLR:
    T_max: 30
    eta_min: 5.0e-05
    last_epoch: -1