trainer:
  logger: True 
  enable_checkpointing: True 
  max_epochs: 100

datamodule:
  t: 
    - 4
  batch_size: 32
  input_size: 512
  train_trans:
    RandomResizedCrop: 
      p: 0.5
      height: 256 
      width: 256
    RandomBrightnessContrast:
      p: 0.5

encoder: resnest50d

optimizer: AdamW
optimizer_params:
  lr: 3.0e-04

scheduler: 
  CosineAnnealingLR:
    T_max: 100
    eta_min: 3.0e-05
    last_epoch: -1