trainer:
  logger: True 
  enable_checkpointing: True 
  max_epochs: 50

datamodule:
  t: 
    - 4
  batch_size: 32
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    Transpose: 
      p: 0.5
    RandomResizedCrop: 
      p: 0.5
      height: 256 
      width: 256
    RandomBrightnessContrast:
      p: 0.5

encoder: resnest50d

optimizer: AdamW
optimizer_params:
  lr: 3.0e-04

scheduler: 
  CosineAnnealingLR:
    T_max: 50
    eta_min: 3.0e-05
    last_epoch: -1