trainer:
  logger: True 
  enable_checkpointing: True 
  max_epochs: 30

datamodule:
  t: 
    - 2 
    - 3
    - 4
  batch_size: 16
  input_size: 384

encoder: resnest50d

optimizer: AdamW
optimizer_params:
  lr: 1.0e-4

scheduler: 
  CosineAnnealingLR:
    T_max: 30
    eta_min: 1.0e-5
    last_epoch: -1