trainer:
  logger: False 
  enable_checkpointing: False 
  max_epochs: 30
  limit_train_batches: 1

datamodule:
  t: 
    - 4
  batch_size: 32
  input_size: 384

encoder: resnest50d

optimizer: AdamW
optimizer_params:
  lr: 3.0e-4

scheduler: 
  CosineAnnealingLR:
    T_max: 30
    eta_min: 3.0e-5
    last_epoch: -1

ckpt_path: checkpoints/resnest50d_t5_384-val_metric=0.60678-epoch=16.ckpt