trainer:
  gpus: 1
  enable_checkpointing: True
  logger: True

backbone: resnest14d

datamodule:
  batch_size: 128
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Transpose:
      p: 0.5
    RandomRotate90:
      p: 0.5
