trainer:
  gpus: 1
  enable_checkpointing: True
  logger: True
  # resume_from_checkpoint: checkpoints/r18rgbnir-val_loss=6.48245-epoch=3.ckpt

datamodule:
  batch_size: 256

backbone: resnet50
early_stopping: True
