trainer:
  logger: True
  enable_checkpointing: True
  max_epochs: 20

datamodule:
  batch_size: 32
  num_workers: 20
  false_color: True
  t: 
    - 4
  train_trans:
    Resize:
      height: 384 
      width: 384

optimizer: AdamW
optimizer_params:
  lr: 0.0001


encoder: resnet34